login:
  organization-id: 12345
  api-token: abcdefgh

#proxy:
#  address: 10.10.10.10
#  port: 8000
#  username: user
#  password: passwd

alarms:
  "12345":
    resources:
#      allUsers: True
      labels:
        - Kraftfahrer: 1
        - CBRN: 1
#      scenarios:
#        - SEG-Alarm
#      units:
#        - B
#    message: Einsatz für den Technischen Zug!
    messageTemplate: SEG-Alarm
    closeEventInHours: 2
